<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[capturing screenshot on failure]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=C:\Users\ivenugopal\GitWorkSpace\DataDrivenFramework//target//surefire-reports//html//Mon_May_17_22_42_58_IST_2021.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[capturing screenshot on failure]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=C:\Users\ivenugopal\GitWorkSpace\DataDrivenFramework//target//surefire-reports//html//Mon_May_17_22_43_06_IST_2021.jpg>Screenshot</a>]]>
    </line>
  </reporter-output>
  <suite started-at="2021-05-17T22:42:55 IST" name="DataDrivenBasics" finished-at="2021-05-17T22:43:06 IST" duration-ms="11753">
    <groups>
    </groups>
    <test started-at="2021-05-17T22:42:55 IST" name="LoginTest" finished-at="2021-05-17T22:42:59 IST" duration-ms="4079">
      <class name="com.w2a.testCases.LoginTest">
        <test-method signature="loginAsBankManager()[pri:0, instance:com.w2a.testCases.LoginTest@7098b907]" started-at="2021-05-17T22:42:55 IST" name="loginAsBankManager" finished-at="2021-05-17T22:42:58 IST" duration-ms="3260" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing after  login test)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing after  login test)
at org.testng.Assert.fail(Assert.java:99)
at com.w2a.testCases.LoginTest.loginAsBankManager(LoginTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[capturing screenshot on failure]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=C:\Users\ivenugopal\GitWorkSpace\DataDrivenFramework//target//surefire-reports//html//Mon_May_17_22_42_58_IST_2021.jpg>Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.w2a.testCases.LoginTest -->
    </test> <!-- LoginTest -->
    <test started-at="2021-05-17T22:42:59 IST" name="Add Customer test" finished-at="2021-05-17T22:43:06 IST" duration-ms="7609">
      <class name="com.w2a.testCases.AddingUsersTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.w2a.testCases.AddingUsersTest@3f1d2e23]" started-at="2021-05-17T22:42:43 IST" name="setup" finished-at="2021-05-17T22:42:55 IST" duration-ms="11624" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="AddUsers(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.w2a.testCases.AddingUsersTest@3f1d2e23]" started-at="2021-05-17T22:43:00 IST" name="AddUsers" data-provider="dataGetter" finished-at="2021-05-17T22:43:06 IST" duration-ms="5344" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Venu]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Gopal]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5a00072]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing after  Adding user test)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing after  Adding user test)
at org.testng.Assert.fail(Assert.java:99)
at com.w2a.testCases.AddingUsersTest.AddUsers(AddingUsersTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[capturing screenshot on failure]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=C:\Users\ivenugopal\GitWorkSpace\DataDrivenFramework//target//surefire-reports//html//Mon_May_17_22_43_06_IST_2021.jpg>Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- AddUsers -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.w2a.testCases.AddingUsersTest@3f1d2e23]" started-at="2021-05-17T22:43:06 IST" name="TearDown" finished-at="2021-05-17T22:43:11 IST" duration-ms="4487" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.w2a.testCases.AddingUsersTest -->
    </test> <!-- Add Customer test -->
  </suite> <!-- DataDrivenBasics -->
</testng-results>
